on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Host Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.7.*
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        tools: 'tools_ninja tools_cmake'
        dir: '${{ runner.temp }}'
        install-deps: 'true'
        cache: true
          
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtinstall: 'git+https://github.com/AlTeveDev/aqtinstall'
        version: 6.7.*
        host: 'linux'
        target: 'desktop'
        arch: 'wasm_singlethread'
        dir: '${{ runner.temp }}'
        install-deps: 'true'
        cache: true

    - name: Build
      run: |
        ls ${{ env.QT_ROOT_DIR }}/..
        export QT_HOST_PATH=${{ env.QT_ROOT_DIR }}/../linux_gcc_64
        ${{ env.QT_ROOT_DIR }}/bin/qt-cmake -B ./build
        cmake --build build
        cd build
        ls
        

    - 
